-- import plugs settings
require('plugins.nvim-tree')
require('plugins.treesitter')
require('plugins.hop')
require('plugins.gitsigns')
require('plugins.lsp')
require('plugins.nvim-cmp')
require('plugins.signature')
require('plugins.luasnip')
require('plugins.lualine')
require('plugins.autopairs')
